allowBuilds:
  canvas: false
  esbuild: set this to true or false
  sharp: set this to true or false
  tesseract.js: true
  unrs-resolver: set this to true or false
  workerd: set this to true or false
